language: java
jdk: openjdk6
cache:
    directories:
    - $HOME/.m2
before_install:
- ./test/bin/travis-install-maven.sh
- psql -U postgres -c "create user dryad_test_user with createdb;"
- createdb -U dryad_test_user dryad_test
- psql dryad_test -U dryad_test_user < ./dspace/etc/postgres/database_schema.sql
- psql dryad_test -U dryad_test_user < ./dspace/etc/postgres/database_create_doi_table.sql
- psql dryad_test -U dryad_test_user < ./dspace/etc/postgres/database_change_payment_system.sql
- psql dryad_test -U dryad_test_user < ./dspace/etc/postgres/database_terms_and_condition.sql
- psql dryad_test -U dryad_test_user < ./dspace/etc/collection-workflow-changes.sql
- psql dryad_test -U dryad_test_user < ./dspace/etc/atmire-versioning-changes.sql
- psql dryad_test -U dryad_test_user < ./dspace/etc/postgres/database_dryad_groups_collections.sql
- psql dryad_test -U dryad_test_user < ./dspace/etc/postgres/database_dryad_registries.sql
- psql dryad_test -U dryad_test_user < ./dspace/etc/postgres/update-sequences.sql
- export PATH="$TRAVIS_BUILD_DIR/apache-maven-2.2.1/bin:$PATH"
install:
- ./test/bin/travis-install-missing-poms.sh
- ./test/bin/travis-install-dryad-dir.sh
before_script:
- "export ITPORT=2341"
- "export SERVER=99"
- "export SCREEN=0"
- "export ITPORT=2341"
- "export DISPLAY=:${SERVER}.${SCREEN}"
- "sh -e /etc/init.d/xvfb start"
- "python -m SimpleHTTPServer $ITPORT > /dev/null 2>&1 &"
script: 
- "mvn install -Dlicense.skip=true -DskipTests=false -Ddefault.dspace.dir=/opt/dryad-test"
- "./test/bin/travis-install-built-poms.sh"
- "mvn -DskipTests=false -f dspace/modules/dryad-widgets/pom.xml failsafe:integration-test failsafe:verify -DseleniumTestURL=\"http://localhost:$ITPORT/dspace/modules/dryad-widgets/dryad-widgets-webapp/src/test/java/it\""
after_script:
- pkill -f SimpleHTTPServer
- sh -e /etc/init.d/xvfb stop
after_failure: find . -type f -path "*/surefire-reports/*" -name "*.txt" -print -exec cat {} \;
notifications:
  slack:
    secure: EqYW7e3FhVxoZzVS4FR52ajePoDbyeOsYcXA9b2BjUWDNc5WNFxRDwNfkxmD09BOAI1g7fKH+Fj5VrtnsUwh7kYosNBj9anjl9CleJ8xGQR35avoaXMJQ3BcULIBfSsUUEwaT+M8uHnM1PNC9DW1uq5w+Hd/9wASwJR5g5BU49I=

